version: '3.9'

volumes:
  scylladb:

services:
  scylladb:
    image: scylladb/scylla:5.4
    container_name: scylladb
    hostname: scylladb
    ports:
      - 9042:9042
      - 9160:9160
    volumes:
      - scylladb:/var/lib/scylla
